project:
  type: website

website:
  title: "Site web Lilou Onno"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: cv.qmd
        text: CV
      - href: projectsL3.qmd
        text: Mes projects     
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false  # Désactive la table des matières



